name: PeopleApp frontend Build and Deploy

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+-*"
      - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Determine Environment Tag Name
        id: script
        run: |
          if [[ ${{ github.ref }} == *"-"* ]]; then 
            TAG=$(echo "${{ github.ref }}" | awk -F"-" '{print $NF}')
          else
            TAG="prod"
          fi
          echo "environment_tag=$TAG"
