name: PeopleApp frontend Build and Deploy

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Echo Environment Tag Name
        run: echo "environment_tag=$TAG" >> $GITHUB_OUTPUT